### PR TITLE
Merge 2.7.73.20 into master

### PR DESCRIPTION
**Pull request by nschiefer**
Merge the changes from #653 into master.

From the original PR against the 2.7.73 release branch:

> This reverts commit 85b09f1.
> This is a temporary fix until all the issues with #647 can be worked through.

### CODE REVIEW

**Comment by alecgrieser** [comment]
I think we also want to revert #647. Arguably, this could be done in a separate PR, but it also might make sense to do this atomically.

In theory, I could do that, if you'd prefer.

**Comment by nschiefer** [comment]
Okay, I think the last commit should revert the changes from #647. Let me know if I messed something up in the conflict resolution.

**Comment by alecgrieser** [comment]
Yeah, the release looks good; arguably there should be a release note saying that the change in 2.7.75 was taken out?

**Comment by nschiefer** [comment]
Good idea. 53bf116 makes a stab at that.

**Pull request merged**
