### PR TITLE
Upgrade FDB to 6.3.12 in RecordLayer 3.0

### PR DESCRIPTION
**Pull request by scottfines**
This is a RecordLayer 3.0 version of PR #1202

### CODE REVIEW

**Comment by alecgrieser** [comment]
Hmm looks like the build failed to start because fdbcli wasn't in the build environment:

```
08:42:33 Unable to build solution without 1 required binaries
08:42:33     fdbcli
```

That should be included in the FoundationDB clients RPM, I thought

**Comment by ammolitor** [comment]
test this please

**Comment by jleach4** [comment]
test this please

**Comment by alecgrieser** [comment]
test this please

**Review by alecgrieser — APPROVED** [review]
Approved, pending PRB passing

**Pull request merged**
