### PR TITLE
Resolves #216: Update guava dependency to 27.0

### LINKED ISSUE #216: Update guava dependency to 27.0
We should update our guava dependency to something more modern. I think 27.0.1 is the latest release, so as long as it doesn't break anything, it seems like it would be a good version to use.

### PR DESCRIPTION
**Pull request by alecgrieser**
This is the newest version of Guava at this time. This has been done against the 2.6 branch to avoid polluting the master branch with this arguably incompatible change.

### CODE REVIEW

**Comment by alecgrieser** [comment]
This resolves #216.

**Comment by alecgrieser** [comment]
Rebase to address merge conflicts

**Comment by alecgrieser** [comment]
@scgray Not sure if you're still having trouble getting PR review request notifications, so here's a ping. But whenever you have time.

**Comment by scgray** [comment]
Hey @alecgrieser, I am monitoring this change--I am just waiting for verification that downstream projects dependent upon this are prepared for the change.

**Comment by alecgrieser** [comment]
Rebase was to address merge conflicts

**Comment by alecgrieser** [comment]
Rebase addresses merge conflicts.

**Comment by alecgrieser** [comment]
Rebase was to address merge conflicts.

**Comment by alecgrieser** [comment]
Rebase was to address merge conflicts.

**Comment by alecgrieser** [comment]
Okay, pushing out to 2.7 to avoid stepping on people who haven't updated their own dependencies yet downstream.

**Pull request closed without merging**
