### PR TITLE
Upgrade RecordLayer to use FDB 6.3.12

### PR DESCRIPTION
**Pull request by scottfines**
Addresses Issue #1201

### CODE REVIEW

**Comment by scottfines** [comment]
This PR will be left in draft status until the FDB 6.3 release is finalized and published.

**Comment by MMcM** [comment]
Should we target the 3.0 branch?

**Comment by scottfines** [comment]
@MMcM I thought about it, but truthfully, right now it feels like there's a good change RL3 will be released before FDB 6.3.11 anyway

**Comment by alecgrieser** [comment]
Looks like 6.3.12 is out in maven central now, if we want to update to that.

**Review by alecgrieser — CHANGES_REQUESTED** [review]
A few minor style things, but otherwise looks good. We should also definitely rebase this onto the 3.0 branch, and then this will be one of the top-line features of 3.0. (We'll probably cut 3.0 right after this is in, but merging it first will make release notes easier, among other things.)

**Comment by scottfines** [comment]
happy to rebase on 3.0, although I would like it if we could add in PRs #1260 and #1261 to the 3.0 release as well, since they make use of new features.

**Comment by alecgrieser** [comment]
Yeah, rebasing all of those makes sense to me

**Comment by scottfines** [comment]
rebase PR here: #1263

**Comment by alecgrieser** [comment]
test this please

**Comment by scottfines** [comment]
test this please

**Comment by scottfines** [comment]
test this please

**Comment by scottfines** [comment]
hey look at that! no more random timeout exceptions. OK, this is good to go

**Comment by alecgrieser** [comment]
Do these changes need to be rebased onto the 3.0 PR?

**Comment by scottfines** [comment]
@alecgrieser  yes, I'm doing that in PR #1263

**Comment by alecgrieser** [comment]
Should we close this PR now that #1263 is merged?

**Pull request closed without merging**
