### PR TITLE
Fix Issue #1395

### PR DESCRIPTION
**Pull request by panghy**

### CODE REVIEW

**Comment by scgray** [comment]
test this please

**Comment by scgray** [comment]
@panghy , I think for the simplicity of this change, maybe it isn't necessary, but as a general note you should update `docs/ReleaseNotes.md` as part each PR, so the fix will be visible in the notes when the release is cut.

**Review by scgray — APPROVED** [review]

**Comment by panghy** [comment]
Updated ReleaseNotes.md

**Comment by scgray** [comment]
test this please

**Review by scgray — APPROVED** [review]

**Pull request merged**
